export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  RATE_LIMITED: "RATE_LIMITED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_NOT_ACTIVE: "PROFILE_NOT_ACTIVE",
  PROFILE_UPDATE_EMPTY: "PROFILE_UPDATE_EMPTY",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
} as const;

export type ErrorCode =
  (typeof ErrorCode)[keyof typeof ErrorCode];